Update GBFS feed url for Valence, Fr
eskerda/pybikes pull request #424
Opened 2021-01-24 22:32 UTC by adrien-delhorme

2021-12-25 20:49 UTC, Altonss commented
It is working fine currently, so why would the url need to be changed?

2022-01-06 10:50 UTC, adrien-delhorme commented
When I request the `feed_url`, I get:
```
{"success":false,"errorCode":"NOT_FOUND","message":"Introuvable","moreInfo":"No handler found for GET /operation/customer/ube/gbfs/v1/en/","fieldsErrors":null}
```

and I can confirm with the official PBSC App that data on https://www.citybik.es/ are not up to date.

But the new url I provided is no longer working... I have no solution for now.

2022-01-06 10:52 UTC, Altonss commented
> and I can confirm with the official PBSC App that data on https://www.citybik.es/ are not up to date.

I don't know why I see this, but on citybik.es the stations of Valence have `  "timestamp": "2022-01-06T10:51:09.424000Z",` as a timestamp. So I thought it is up to date...

2022-01-06 10:55 UTC, Altonss commented
This url is working!! https://valence.publicbikesystem.net/ube/gbfs/v1/

2022-01-06 10:58 UTC, Altonss requested changes
Here is the review with the updated url, hope the data is up to date!

2022-01-06 10:58 UTC, Altonss commented on pybikes/data/gbfs.json
> +            "feed_url": "https://valencefr.publicbikesystem.net/ube/gbfs/v1/en/"
```suggestion
            "feed_url": "https://valencefr.publicbikesystem.net/ube/gbfs/v1/"
```

2022-01-06 11:03 UTC, adrien-delhorme commented
You are right, I figured out that PBSC is no longer the official app in Valence, Fr. The data I checked were outdated. There is another official app now, and it is already up to date with Citybik.es... So it seems it is already working with the current feed_url (don't know why).

2022-01-06 11:07 UTC, Altonss commented
> You are right, I figured out that PBSC is no longer the official app in Valence, Fr. The data I checked were outdated. There is another official app now, and it is already up to date with Citybik.es... So it seems it is already working with the current feed_url (don't know why).

But somehow I cannot open the link with the /en/, so maybe it would be good to merge this PR with my suggestion!
I see that on https://valence.publicbikesystem.net/ube/gbfs/v1/ the links of the different data are to valencefr, so we should merge this PR :)

2022-01-07 12:03 UTC, merged