Fix Velopop (Avignon)
eskerda/pybikes pull request #517
Opened 2022-12-20 16:54 UTC by Manu1400

documentation: https://transport.data.gouv.fr/datasets/velos-libre-service-grand-avignon-velopop-disponibilite-en-temps-reel

2022-12-25 19:08 UTC, eUgEntOptIc44 requested changes

2022-12-25 19:08 UTC, eUgEntOptIc44 commented on pybikes/data/gbfs.json
> +            "feed_url":"https://avignon-gbfs.klervi.net/gbfs/en/station_information.json"
the `feed_url` should be `https://avignon-gbfs.klervi.net/gbfs/en/gbfs.json` to match the criteria of the [gbfs.py](https://github.com/eskerda/pybikes/blob/97414d1c9f3ebef6cf96e8637b15a77820d32612/pybikes/gbfs.py) parser.

2022-12-25 19:08 UTC, eUgEntOptIc44 commented
just tested the gbfs feed at [`https://avignon-gbfs.klervi.net/gbfs/en/station_information.json`](https://avignon-gbfs.klervi.net/gbfs/en/station_information.json) and noticed 2 `stations` featuring **invalid** coordinates:

```json
// snippet from (archived) source: https://web.archive.org/web/20221225185948/https://avignon-gbfs.klervi.net/gbfs/en/station_information.json
{
	"station_id": "999_028",
	"name": "Médiathèque",
	"lat": null,
	"lon": null,
	"capacity": 24
}, {
	"station_id": "999_032",
	"name": "Olivades",
	"lat": null,
	"lon": null,
	"capacity": 16
}
```

This returns a `TypeError` when trying to parse to `float` in [gbfs.py](https://github.com/eskerda/pybikes/blob/97414d1c9f3ebef6cf96e8637b15a77820d32612/pybikes/gbfs.py#L145).

2022-12-29 15:57 UTC, eskerda commented
> just tested the gbfs feed at [`https://avignon-gbfs.klervi.net/gbfs/en/station_information.json`](https://avignon-gbfs.klervi.net/gbfs/en/station_information.json) and noticed 2 `stations` featuring **invalid** coordinates:
> 
> ```json
> // snippet from (archived) source: https://web.archive.org/web/20221225185948/https://avignon-gbfs.klervi.net/gbfs/en/station_information.json
> {
> 	"station_id": "999_028",
> 	"name": "Médiathèque",
> 	"lat": null,
> 	"lon": null,
> 	"capacity": 24
> }, {
> 	"station_id": "999_032",
> 	"name": "Olivades",
> 	"lat": null,
> 	"lon": null,
> 	"capacity": 16
> }
> ```
> 
> This returns a `TypeError` when trying to parse to `float` in [gbfs.py](https://github.com/eskerda/pybikes/blob/97414d1c9f3ebef6cf96e8637b15a77820d32612/pybikes/gbfs.py#L145).

We can try to filter these... let me think of something. Thanks for checking!

2023-01-05 18:23 UTC, eUgEntOptIc44 commented
> We can try to filter these... let me think of something. Thanks for checking!

Hi @eskerda,

As noted above I just published my appoarch to solve this in a new PR. Hope you might have the time to provide me with some feedback on this. 
Regards,
Jean-Luc

2023-01-08 00:25 UTC, closed without merging