Kiel Sprottenflotte changed from Nextbike to Donkey Republic
eskerda/pybikes pull request #604
Opened 2023-09-08 18:09 UTC by patzi

Operator changed in Kiel see sprottenflotte.de or https://www.donkey.bike/de/stadte/kiel/

2023-09-12 12:43 UTC, eskerda commented on pybikes/data/gbfs.json
> +            "tag": "donkey-kiel",
If it's the same system, let's keep the previous tag `sprottenflotte-kiel`

2023-09-12 12:46 UTC, eskerda requested changes
Hey @patzi, see comment for a minor change, the rest looks good. Thanks for contributing!

2023-09-13 09:57 UTC, patzi reviewed
Fixed this, I thought the tags would be operator specific. Thanks :)

2023-09-13 10:03 UTC, merged

2023-09-13 10:03 UTC, eskerda commented
No worries, thanks!