Fix slovnaft-bajk
eskerda/pybikes pull request #657
Opened 2023-12-17 21:56 UTC by martgnz

Closes https://github.com/eskerda/pybikes/issues/598.

2023-12-18 16:19 UTC, eskerda requested changes

2023-12-18 16:19 UTC, eskerda commented on pybikes/slovnaft_bajk.py
> +
```suggestion
```

2023-12-18 16:19 UTC, eskerda commented on pybikes/slovnaft_bajk.py
> +from pybikes.base import BikeShareSystem, BikeShareStation
```suggestion
from pybikes.base import BikeShareSystem, BikeShareStation, PyBikesScraper
```

2023-12-18 16:19 UTC, eskerda commented on pybikes/slovnaft_bajk.py
> +from pybikes import utils
```suggestion
```

2023-12-18 16:19 UTC, eskerda commented on pybikes/slovnaft_bajk.py
> +        scraper = scraper or utils.PyBikesScraper()
```suggestion
        scraper = scraper or PyBikesScraper()
```

2023-12-20 11:13 UTC, martgnz commented
Thanks for your review. I copied from an old system that had all those imports. Will remember for the next one.

2023-12-21 18:49 UTC, merged